/**
 * A curated emoji set aimed at worldbuilding rather than the full Unicode
 * catalogue, which would add well over a hundred kilobytes for symbols nobody
 * reaches for when describing a planet or a sword.
 *
 * Keywords are English so search behaves the same in both interface languages;
 * the Turkish column carries the terms a Turkish-speaking author would type.
 */
export interface EmojiEntry {
	char: string;
	en: string;
	tr: string;
}

export interface EmojiCategory {
	id: string;
	en: string;
	tr: string;
	entries: EmojiEntry[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
	{
		id: "people",
		en: "People",
		tr: "İnsanlar",
		entries: [
			{ char: "👤", en: "person silhouette character", tr: "kişi karakter siluet" },
			{ char: "👥", en: "people group crowd", tr: "insanlar grup kalabalık" },
			{ char: "🧑", en: "person adult", tr: "kişi yetişkin" },
			{ char: "👴", en: "old man elder", tr: "yaşlı adam ihtiyar" },
			{ char: "👵", en: "old woman elder", tr: "yaşlı kadın ihtiyar" },
			{ char: "👶", en: "baby child infant", tr: "bebek çocuk" },
			{ char: "🧒", en: "child kid", tr: "çocuk" },
			{ char: "🤴", en: "prince royal noble", tr: "prens soylu asil" },
			{ char: "👸", en: "princess royal noble queen", tr: "prenses soylu kraliçe" },
			{ char: "🫅", en: "monarch crown ruler king", tr: "hükümdar taç kral" },
			{ char: "🧙", en: "mage wizard sorcerer", tr: "büyücü sihirbaz" },
			{ char: "🧝", en: "elf fae", tr: "elf peri" },
			{ char: "🧛", en: "vampire undead", tr: "vampir" },
			{ char: "🧟", en: "zombie undead", tr: "zombi ölü" },
			{ char: "🧞", en: "genie spirit djinn", tr: "cin ruh" },
			{ char: "🧜", en: "merfolk mermaid sea", tr: "denizkızı" },
			{ char: "🧚", en: "fairy sprite", tr: "peri" },
			{ char: "🥷", en: "ninja assassin shadow", tr: "ninja suikastçı gölge" },
			{ char: "🕵️", en: "detective spy investigator", tr: "dedektif casus" },
			{ char: "💂", en: "guard soldier sentry", tr: "muhafız asker nöbetçi" },
			{ char: "👷", en: "worker builder engineer", tr: "işçi inşaatçı mühendis" },
			{ char: "🧑‍🚀", en: "astronaut spacefarer pilot", tr: "astronot uzaycı pilot" },
			{ char: "🧑‍🔬", en: "scientist researcher", tr: "bilim insanı araştırmacı" },
			{ char: "🧑‍⚕️", en: "doctor healer medic", tr: "doktor şifacı" },
			{ char: "🧑‍🌾", en: "farmer peasant", tr: "çiftçi köylü" },
			{ char: "🧑‍🎨", en: "artist painter", tr: "sanatçı ressam" },
			{ char: "🗿", en: "statue monument idol", tr: "heykel anıt put" },
			{ char: "💀", en: "skull death dead", tr: "kafatası ölüm" },
			{ char: "☠️", en: "skull crossbones poison danger", tr: "korsan zehir tehlike" },
			{ char: "👻", en: "ghost spirit phantom", tr: "hayalet ruh" },
			{ char: "👽", en: "alien extraterrestrial", tr: "uzaylı" },
			{ char: "👾", en: "alien monster invader", tr: "uzaylı canavar istilacı" },
			{ char: "🤖", en: "robot android machine", tr: "robot android makine" },
			{ char: "😈", en: "demon devil imp", tr: "şeytan iblis" },
			{ char: "👹", en: "ogre oni demon", tr: "dev iblis" },
			{ char: "👺", en: "goblin tengu", tr: "goblin" },
			{ char: "🎭", en: "masks theatre identity disguise", tr: "maske tiyatro kimlik" },
		],
	},
	{
		id: "creatures",
		en: "Creatures",
		tr: "Yaratıklar",
		entries: [
			{ char: "🐉", en: "dragon wyrm", tr: "ejderha" },
			{ char: "🐲", en: "dragon face", tr: "ejderha yüz" },
			{ char: "🦖", en: "dinosaur rex beast", tr: "dinozor canavar" },
			{ char: "🦕", en: "dinosaur sauropod", tr: "dinozor" },
			{ char: "🐺", en: "wolf beast", tr: "kurt" },
			{ char: "🦅", en: "eagle bird raptor", tr: "kartal kuş" },
			{ char: "🦉", en: "owl bird night", tr: "baykuş kuş gece" },
			{ char: "🐍", en: "snake serpent", tr: "yılan" },
			{ char: "🕷️", en: "spider arachnid", tr: "örümcek" },
			{ char: "🦂", en: "scorpion", tr: "akrep" },
			{ char: "🦇", en: "bat night", tr: "yarasa gece" },
			{ char: "🐙", en: "octopus tentacle kraken", tr: "ahtapot dokunaç" },
			{ char: "🦈", en: "shark predator", tr: "köpekbalığı yırtıcı" },
			{ char: "🐋", en: "whale leviathan", tr: "balina" },
			{ char: "🦁", en: "lion beast", tr: "aslan" },
			{ char: "🐅", en: "tiger beast", tr: "kaplan" },
			{ char: "🐻", en: "bear beast", tr: "ayı" },
			{ char: "🐎", en: "horse steed mount", tr: "at binek" },
			{ char: "🦌", en: "deer stag", tr: "geyik" },
			{ char: "🐗", en: "boar", tr: "yaban domuzu" },
			{ char: "🦏", en: "rhino beast", tr: "gergedan" },
			{ char: "🐘", en: "elephant", tr: "fil" },
			{ char: "🦂", en: "scorpion venom", tr: "akrep zehir" },
			{ char: "🪰", en: "insect fly swarm", tr: "sinek böcek sürü" },
			{ char: "🐜", en: "ant swarm colony", tr: "karınca koloni" },
			{ char: "🦋", en: "butterfly transformation", tr: "kelebek dönüşüm" },
			{ char: "🪱", en: "worm larva", tr: "solucan kurtçuk" },
			{ char: "🐢", en: "turtle ancient slow", tr: "kaplumbağa kadim" },
			{ char: "🦎", en: "lizard reptile", tr: "kertenkele sürüngen" },
			{ char: "🐦", en: "bird", tr: "kuş" },
			{ char: "🦚", en: "peacock display", tr: "tavuskuşu" },
			{ char: "🐁", en: "mouse rat vermin", tr: "fare" },
		],
	},
	{
		id: "space",
		en: "Space",
		tr: "Uzay",
		entries: [
			{ char: "🌌", en: "galaxy milky way universe", tr: "galaksi samanyolu evren" },
			{ char: "🪐", en: "planet ringed saturn", tr: "gezegen halkalı satürn" },
			{ char: "🌍", en: "earth world globe", tr: "dünya küre" },
			{ char: "🌎", en: "earth americas world", tr: "dünya" },
			{ char: "🌏", en: "earth asia world", tr: "dünya asya" },
			{ char: "🌑", en: "new moon dark", tr: "yeni ay karanlık" },
			{ char: "🌒", en: "waxing crescent moon", tr: "hilal ay" },
			{ char: "🌓", en: "half moon quarter", tr: "yarım ay" },
			{ char: "🌔", en: "gibbous moon", tr: "ay" },
			{ char: "🌕", en: "full moon", tr: "dolunay" },
			{ char: "🌘", en: "waning crescent moon", tr: "hilal ay" },
			{ char: "☀️", en: "sun star day", tr: "güneş yıldız gündüz" },
			{ char: "⭐", en: "star", tr: "yıldız" },
			{ char: "🌟", en: "glowing star bright", tr: "parlak yıldız" },
			{ char: "✨", en: "sparkles magic shine", tr: "parıltı büyü" },
			{ char: "💫", en: "dizzy comet trail", tr: "kuyruklu yıldız" },
			{ char: "☄️", en: "comet meteor impact", tr: "kuyrukluyıldız meteor çarpma" },
			{ char: "🌠", en: "shooting star wish", tr: "kayan yıldız dilek" },
			{ char: "🚀", en: "rocket ship launch", tr: "roket gemi fırlatma" },
			{ char: "🛸", en: "ufo saucer alien craft", tr: "ufo daire uzay aracı" },
			{ char: "🛰️", en: "satellite orbit station", tr: "uydu yörünge" },
			{ char: "🔭", en: "telescope observatory", tr: "teleskop gözlemevi" },
			{ char: "🌐", en: "globe network world", tr: "küre ağ dünya" },
			{ char: "⚫", en: "black hole void dark", tr: "kara delik boşluk" },
		],
	},
	{
		id: "nature",
		en: "Nature",
		tr: "Doğa",
		entries: [
			{ char: "🌋", en: "volcano eruption fire mountain", tr: "yanardağ volkan patlama" },
			{ char: "🏔️", en: "mountain snow peak", tr: "dağ kar zirve" },
			{ char: "⛰️", en: "mountain peak", tr: "dağ zirve" },
			{ char: "🏜️", en: "desert dune wasteland", tr: "çöl kumul çorak" },
			{ char: "🏝️", en: "island tropical", tr: "ada tropik" },
			{ char: "🌊", en: "wave ocean sea water", tr: "dalga okyanus deniz su" },
			{ char: "🌫️", en: "fog mist haze", tr: "sis pus" },
			{ char: "🌪️", en: "tornado storm cyclone", tr: "kasırga hortum fırtına" },
			{ char: "⛈️", en: "storm thunder rain", tr: "fırtına gök gürültüsü yağmur" },
			{ char: "⚡", en: "lightning bolt energy power", tr: "şimşek yıldırım enerji güç" },
			{ char: "🔥", en: "fire flame burn", tr: "ateş alev yanmak" },
			{ char: "❄️", en: "snowflake ice cold frost", tr: "kar buz soğuk don" },
			{ char: "💧", en: "water drop liquid", tr: "su damla sıvı" },
			{ char: "🌱", en: "seedling sprout growth", tr: "fide filiz büyüme" },
			{ char: "🌳", en: "tree forest wood", tr: "ağaç orman" },
			{ char: "🌲", en: "evergreen pine forest", tr: "çam ağaç orman" },
			{ char: "🍂", en: "leaves autumn decay fall", tr: "yaprak sonbahar çürüme" },
			{ char: "🌺", en: "flower bloom", tr: "çiçek" },
			{ char: "🍄", en: "mushroom fungus spore", tr: "mantar spor" },
			{ char: "🪨", en: "rock stone boulder", tr: "kaya taş" },
			{ char: "🕳️", en: "hole pit abyss void", tr: "delik çukur uçurum" },
			{ char: "🌅", en: "sunrise dawn beginning", tr: "gün doğumu şafak başlangıç" },
			{ char: "🌇", en: "sunset dusk ending", tr: "gün batımı akşam son" },
			{ char: "🌈", en: "rainbow spectrum", tr: "gökkuşağı tayf" },
		],
	},
	{
		id: "objects",
		en: "Objects",
		tr: "Nesneler",
		entries: [
			{ char: "⚔️", en: "swords battle war duel", tr: "kılıç savaş düello" },
			{ char: "🗡️", en: "dagger blade knife", tr: "hançer bıçak" },
			{ char: "🛡️", en: "shield defence protection", tr: "kalkan savunma koruma" },
			{ char: "🏹", en: "bow arrow archer", tr: "yay ok okçu" },
			{ char: "🪓", en: "axe chop weapon", tr: "balta" },
			{ char: "🔫", en: "gun firearm weapon", tr: "silah tabanca" },
			{ char: "💣", en: "bomb explosive", tr: "bomba patlayıcı" },
			{ char: "🧨", en: "dynamite explosive fuse", tr: "dinamit fitil" },
			{ char: "🔱", en: "trident spear divine", tr: "üç dişli mızrak ilahi" },
			{ char: "👑", en: "crown king queen royal rule", tr: "taç kral kraliçe hükümdar" },
			{ char: "💍", en: "ring jewel band", tr: "yüzük mücevher" },
			{ char: "💎", en: "gem crystal jewel", tr: "mücevher kristal elmas" },
			{ char: "🔮", en: "crystal ball divination prophecy", tr: "kristal küre kehanet fal" },
			{ char: "🪬", en: "amulet charm ward", tr: "muska nazarlık tılsım" },
			{ char: "🧿", en: "evil eye ward talisman", tr: "nazar boncuğu tılsım" },
			{ char: "⚗️", en: "alembic alchemy potion", tr: "imbik simya iksir" },
			{ char: "🧪", en: "test tube experiment potion", tr: "deney tüpü iksir" },
			{ char: "🗝️", en: "key unlock secret", tr: "anahtar sır kilit" },
			{ char: "🔒", en: "lock sealed closed", tr: "kilit mühürlü kapalı" },
			{ char: "📜", en: "scroll law decree ancient text", tr: "parşömen yasa ferman kadim metin" },
			{ char: "📖", en: "book open story tome", tr: "kitap açık hikaye" },
			{ char: "📕", en: "book closed tome volume", tr: "kitap cilt" },
			{ char: "🕯️", en: "candle light ritual", tr: "mum ışık ayin" },
			{ char: "🏺", en: "amphora vessel relic ancient", tr: "amfora kap kalıntı kadim" },
			{ char: "⚙️", en: "gear machine mechanism", tr: "dişli makine mekanizma" },
			{ char: "🔧", en: "wrench tool repair", tr: "anahtar alet tamir" },
			{ char: "⛓️", en: "chains bound prison", tr: "zincir bağlı hapis" },
			{ char: "🪞", en: "mirror reflection portal", tr: "ayna yansıma geçit" },
			{ char: "🧭", en: "compass navigation direction", tr: "pusula yön" },
			{ char: "🗺️", en: "map atlas exploration", tr: "harita keşif" },
			{ char: "⏳", en: "hourglass time passing", tr: "kum saati zaman" },
			{ char: "⌛", en: "hourglass done time", tr: "kum saati zaman" },
			{ char: "🕰️", en: "clock time chronology", tr: "saat zaman kronoloji" },
			{ char: "🎲", en: "dice chance fate", tr: "zar şans kader" },
			{ char: "🔗", en: "link connection chain", tr: "bağlantı halka" },
		],
	},
	{
		id: "places",
		en: "Places",
		tr: "Mekânlar",
		entries: [
			{ char: "🏰", en: "castle fortress keep", tr: "kale şato" },
			{ char: "🏯", en: "castle japanese fortress", tr: "kale japon" },
			{ char: "🗼", en: "tower spire", tr: "kule" },
			{ char: "🏛️", en: "temple classical senate hall", tr: "tapınak meclis salon" },
			{ char: "⛩️", en: "shrine gate torii", tr: "tapınak kapı" },
			{ char: "🕌", en: "mosque dome", tr: "cami kubbe" },
			{ char: "⛪", en: "church chapel", tr: "kilise şapel" },
			{ char: "🏚️", en: "ruin abandoned derelict", tr: "harabe terk edilmiş viran" },
			{ char: "🏘️", en: "village houses settlement", tr: "köy yerleşim evler" },
			{ char: "🏙️", en: "city skyline metropolis", tr: "şehir metropol" },
			{ char: "🌆", en: "city dusk skyline", tr: "şehir akşam" },
			{ char: "🏭", en: "factory industry", tr: "fabrika sanayi" },
			{ char: "🏗️", en: "construction building site", tr: "inşaat şantiye" },
			{ char: "🚪", en: "door entrance threshold", tr: "kapı giriş eşik" },
			{ char: "🌉", en: "bridge crossing", tr: "köprü geçit" },
			{ char: "🛤️", en: "railway tracks path", tr: "demiryolu ray yol" },
			{ char: "⚓", en: "anchor port harbour", tr: "çapa liman" },
			{ char: "🏕️", en: "camp tent outpost", tr: "kamp çadır karakol" },
			{ char: "🕋", en: "cube sacred site", tr: "kutsal yapı" },
			{ char: "🗻", en: "sacred mountain peak", tr: "kutsal dağ zirve" },
		],
	},
	{
		id: "concepts",
		en: "Concepts",
		tr: "Kavramlar",
		entries: [
			{ char: "💭", en: "thought idea concept draft", tr: "düşünce fikir konsept taslak" },
			{ char: "💡", en: "idea insight lightbulb", tr: "fikir aydınlanma ampul" },
			{ char: "🧠", en: "brain mind intelligence", tr: "beyin zihin zekâ" },
			{ char: "❤️", en: "heart love bond", tr: "kalp aşk bağ" },
			{ char: "💔", en: "broken heart loss betrayal", tr: "kırık kalp kayıp ihanet" },
			{ char: "☯️", en: "balance duality yin yang", tr: "denge ikilik" },
			{ char: "♾️", en: "infinity eternal endless", tr: "sonsuzluk ebedi" },
			{ char: "⚖️", en: "scales justice law balance", tr: "terazi adalet yasa denge" },
			{ char: "🧬", en: "dna genetics species life", tr: "dna genetik tür yaşam" },
			{ char: "☢️", en: "radiation nuclear hazard", tr: "radyasyon nükleer tehlike" },
			{ char: "☣️", en: "biohazard plague contagion", tr: "biyolojik tehlike salgın" },
			{ char: "🌀", en: "spiral vortex portal cycle", tr: "sarmal girdap geçit döngü" },
			{ char: "🕸️", en: "web network trap", tr: "ağ tuzak" },
			{ char: "🩸", en: "blood wound sacrifice", tr: "kan yara kurban" },
			{ char: "👁️", en: "eye watching sight vision", tr: "göz izleme görüş" },
			{ char: "🗣️", en: "speech voice rumour", tr: "konuşma ses söylenti" },
			{ char: "🤝", en: "handshake alliance pact treaty", tr: "el sıkışma ittifak anlaşma" },
			{ char: "⚡", en: "power energy force", tr: "güç enerji kuvvet" },
			{ char: "🏳️", en: "flag surrender neutral", tr: "bayrak teslim tarafsız" },
			{ char: "🚩", en: "flag marker claim", tr: "bayrak işaret" },
			{ char: "❓", en: "question unknown mystery", tr: "soru bilinmeyen gizem" },
			{ char: "⚠️", en: "warning caution danger", tr: "uyarı dikkat tehlike" },
			{ char: "🔱", en: "authority divine power", tr: "otorite ilahi güç" },
			{ char: "🎯", en: "target goal objective", tr: "hedef amaç" },
		],
	},
];

const ALL_ENTRIES: EmojiEntry[] = EMOJI_CATEGORIES.flatMap((category) => category.entries);

export function searchEmoji(query: string): EmojiEntry[] {
	const needle = query.trim().toLowerCase();
	if (!needle) return ALL_ENTRIES;
	return ALL_ENTRIES.filter(
		(entry) =>
			entry.char === needle ||
			entry.en.includes(needle) ||
			entry.tr.includes(needle),
	);
}
